apiVersion: v1
kind: Pod
metadata:
  name: podspringbootmavenexample
  labels:
    appname: mavan
spec:
  containers:
    - name: springbootmavenexample-container
      image: kanisara/springbootmavenexample
      ports:
      - containerPort: 8080
...
---
apiVersion: v1
kind: Service
metadata:
  name: httpdnodeportservice
spec:
  selector:
    appname: mavan              #-- > Label of pod
  type: NodePort
  ports:
  - port: 80                    #--> Service Port
    targetPort: 8080              #--> Container Port
    nodePort: 30300